services:
  surveys:
    build: ./Backend/SurveyService
    ports: 
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
  responses:
    build: ./Backend/ResponseService
    ports: 
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
  messaging:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  api-gateway:
    build: ./Backend/ApiGateway
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
    